### ISSUE TITLE
Developer - Can't get the application compile

### ISSUE THREAD

**Issue by sandyw219** [FriesI23/mhabit#195]
Hi!

I am trying to run this application locally, but Android Studio/Dart detects thousands of errors throughout the documents, which I'm assuming is because I set it up wrong. Any idea how I can get the code running? Or to compile I guess? I've tried everything I can think of and don't have any direction for what to try next. Let me know if I can provide any more information. Thanks in advance!

**Hardware & software details:**
Operating system stuff: Fedora 40 KDE
Laptop: Lenovo Ideapad gaming 3
GPU: nvidia
CPU: AMD RYZEN 7

**Here is how I set it up:** 
Android Studios was installed through Flatpak on Discover (Fedora). I installed flutter 3.19.6 from the given link and configured it with no issue. I am able to run a basic Flutter app (the default one when making a flutter app) on the android emulator through android studio without issue. As instructed on the readme, I needed to download libsqlite3-0 and dev, however I'm not using Ubuntu I'm using Fedora so I got the Fedora version: libsqlite3x and libsqlite3x-devel. I downloaded the zip file of the code from the mhabit main branch, extracted and opened it in android studio, got an emulator running as the target selector, opened the lib/view/main.dart file as my config selector. Then I clicked run. I got this same error when running from the console as described in the readme. (Also I've restarted a bunch so everything is up to date)

`$ flutter --version
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (5 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
`
`
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on Fedora Linux 40 (KDE Plasma) 6.10.7-200.fc40.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 2 categories.
(I don't plan on developing for the web so I don't need chrome, and it seems that being unable to detect my android studio version is a non-issue)
`

`$ flutter config --list
All Settings:
  enable-web: true
  enable-linux-desktop: true
  enable-macos-desktop: true
  enable-windows-desktop: true
  enable-android: true
  enable-ios: true
  enable-fuchsia: false (Unavailable)
  enable-custom-devices: (Not set)
  cli-animations: (Not set)
  enable-native-assets: (Not set) (Unavailable)
  enable-flutter-preview: (Not set) (Unavailable)
  android-studio-dir: /var/lib/flatpak/app/com.google.AndroidStudio/current/active/files/extra/android-studio
`

**Here are the errors:**
terminal output:
`Expected /home/sandy/Code/seepee/mhabit-main/l10n.yaml to contain a map, instead was ./configs/l10n.yaml`
Dart's errors:
![image](https://github.com/user-attachments/assets/5b11c82d-0a6c-4eb6-b000-66d41f9677c9)
There are many more errors than the ones shown, but I doubt it's necessary to see the rest. Const variables must be initialized with a constant value, invalid constant value, mixin can only be applied to class, no associated named super constructor parameter, etc.

**These are errors shown during this time when I run android studios from konsole:**
`2024-09-09 16:51:38,482 [ 228967]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2024-09-09 16:51:38,498 [ 228983]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - use other group instead of unexpected one: testing.instrumented.configuration
2024-09-09 16:51:38,499 [ 228984]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - Use <groupConfigurable> to specify custom configurable group: other
2024-09-09 16:51:38,499 [ 228984]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - use other group instead of unexpected one: project.propCompiler
2024-09-09 16:51:39,521 [ 230006]   WARN - #c.i.i.p.n.PluginLogo - Cannot load plugin icon (file=/app/extra/android-studio/plugins/Groovy/lib/console.groovy/META-INF/pluginIcon.svg)
java.nio.file.FileSystemException: /app/extra/android-studio/plugins/Groovy/lib/console.groovy/META-INF/pluginIcon.svg: Not a directory
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
        at com.intellij.ide.plugins.newui.PluginLogoKt.tryLoadIcon(PluginLogo.kt:339)
        at com.intellij.ide.plugins.newui.PluginLogoKt.tryLoadDirIcons(PluginLogo.kt:252)
        at com.intellij.ide.plugins.newui.PluginLogoKt.loadPluginIconsFromFile(PluginLogo.kt:235)
        at com.intellij.ide.plugins.newui.PluginLogoKt.access$loadPluginIconsFromFile(PluginLogo.kt:1)
        at com.intellij.ide.plugins.newui.PluginLogoLoader$schedulePluginIconLoading$1$1.invokeSuspend(PluginLogo.kt:385)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-09-09 16:51:39,523 [ 230008]   WARN - #c.i.i.p.n.PluginLogo - Cannot load plugin icon (file=/app/extra/android-studio/plugins/Groovy/lib/console.groovy/META-INF/pluginIcon_dark.svg)
java.nio.file.FileSystemException: /app/extra/android-studio/plugins/Groovy/lib/console.groovy/META-INF/pluginIcon_dark.svg: Not a directory
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
        at com.intellij.ide.plugins.newui.PluginLogoKt.tryLoadIcon(PluginLogo.kt:339)
        at com.intellij.ide.plugins.newui.PluginLogoKt.tryLoadDirIcons(PluginLogo.kt:253)
        at com.intellij.ide.plugins.newui.PluginLogoKt.loadPluginIconsFromFile(PluginLogo.kt:235)
        at com.intellij.ide.plugins.newui.PluginLogoKt.access$loadPluginIconsFromFile(PluginLogo.kt:1)
        at com.intellij.ide.plugins.newui.PluginLogoLoader$schedulePluginIconLoading$1$1.invokeSuspend(PluginLogo.kt:385)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-09-09 16:51:39,823 [ 230308] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Intention Description Dir URL is null: Create Preview; ComposeCreatePreviewActionK1; while looking for description.html [Plugin: androidx.compose.plugins.idea]
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Create Preview; ComposeCreatePreviewActionK1; while looking for description.html [Plugin: androidx.compose.plugins.idea]
        at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:62)
        at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:132)
        at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.kt:84)
        at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$0(SearchableOptionsRegistrarImpl.java:137)
        at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:61)
        at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:137)
        at com.intellij.openapi.options.newEditor.SettingsFilter.lambda$new$1(SettingsFilter.java:59)
        at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-09-09 16:51:39,824 [ 230309] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Android Studio Koala Feature Drop | 2024.1.2  Build #AI-241.18034.62.2412.12266719
2024-09-09 16:51:39,824 [ 230309] SEVERE - #c.i.o.e.i.ExtensionPointImpl - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-09-09 16:51:39,824 [ 230309] SEVERE - #c.i.o.e.i.ExtensionPointImpl - OS: Linux
2024-09-09 16:51:39,824 [ 230309] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Last Action: WelcomeScreen.Plugins
2024-09-09 16:51:44,672 [ 235157]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
`

**Comment by FriesI23** [comment]
Sorry for late response. Plz try building again using the latest main branch. I fixed some bugs causing build failures on Linux.
